### ISSUE TITLE
model  CTL-4100WL

### ISSUE THREAD

**Issue by cometta** [thenickdude/wacom-driver-fix#41]
when i installed the orignal wacom driver on catalina, after rebooted, it just fail to load into the desktop. May i know does this repo workaround driver fix the issue? 

ref: https://www.wacom.com/en-us/products/pen-tablets/wacom-intuos

**Comment by thenickdude** [comment]
Hi there,

That problem seems to happen randomly across all modern Wacom models when the driver cache is rebuilt at the end of driver installation. I haven't seen it happen myself, so I haven't been able to investigate, but it's likely that it is not even the Wacom driver at fault - just that the driver cache didn't rebuild properly due to some macOS fault, and then this spells the end for macOS because the broken cache prevents it from booting. Unfortunately this also tends to ruin the macOS Recovery environment, which makes it a pain to recover from.

I believe you should be able to boot into the macOS "Internet Recovery" mode described here and use that to reinstall macOS:

https://support.apple.com/en-nz/HT201314

I'm unsure on the exact details of Internet Recovery mode, but if it works like regular recovery, it allows you to reinstall macOS to make your computer bootable again while keeping your personal data intact. You may want to get Apple to confirm this or to perform this reinstall for you.

After reinstalling macOS I would probably just go ahead and try installing the driver for your CTL-4100WL again, I don't think the problem would recur.

Unfortunately none of my modified drivers support this modern model.
